[theme]
base = "dark"
primaryColor = "#35B8FF"
backgroundColor = "#060A11"
secondaryBackgroundColor = "#101823"
textColor = "#F4F7FB"
font = "sans-serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false